<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Seeder;

class PoultryPricingSettingsSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            [
                'key' => 'poultry_pricing.concrete_cost_per_m2',
                'value' => '850',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'تكلفة المتر المربع للخرسانات',
                'label_en' => 'Concrete cost per m²',
                'description' => 'سعر المتر المربع للخرسانات في الإنشاءات',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 1,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.steel_cost_per_m2',
                'value' => '1200',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'تكلفة المتر المربع للاستيل',
                'label_en' => 'Steel cost per m²',
                'description' => 'سعر المتر المربع للاستيل في الإنشاءات',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 2,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.wall_cost_per_m2',
                'value' => '650',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'تكلفة المتر المربع للحوائط',
                'label_en' => 'Wall cost per m²',
                'description' => 'سعر المتر المربع للحوائط',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 3,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.tanks_fixed_cost',
                'value' => '400000',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'تكلفة الخزانات الثابتة',
                'label_en' => 'Tanks fixed cost',
                'description' => 'بند ثابت لمجموعة خزانات المياه (شرب، أدوية، تبريد، سولار) — يُضاف كمقطوعة واحدة',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 4,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.price_per_bird',
                'value' => '95',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'سعر الطائر (بطارية)',
                'label_en' => 'Price per bird',
                'description' => 'سعر الطائر الواحد في نظام البطاريات',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 5,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.birds_per_cage_unit',
                'value' => '16',
                'type' => 'integer',
                'category' => 'poultry_pricing',
                'label_ar' => 'عدد الطيور لكل وحدة قفص',
                'label_en' => 'Birds per cage unit',
                'description' => 'عدد الطيور في كل وحدة قفص واحدة',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 6,
                'validation_rules' => ['numeric', 'min:1'],
            ],
            [
                'key' => 'poultry_pricing.dead_zone_meters',
                'value' => '6',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'المنطقة الميتة (تخصم من الطول)',
                'label_en' => 'Dead zone meters',
                'description' => 'الطول المخصوم من العنبر لحساب عدد الطيور',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 7,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.back_fan_bird_ratio',
                'value' => '2.1',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'نسبة الشفاطات الخلفية للطيور',
                'label_en' => 'Back fan bird ratio',
                'description' => 'معامل حجم التهوية لكل طائر',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 8,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.back_fan_capacity',
                'value' => '5000',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'سعة الشفاط الخلفي',
                'label_en' => 'Back fan capacity',
                'description' => 'سعة التهوية لكل شفاط خلفي (m³/h)',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 9,
                'validation_rules' => ['numeric', 'min:1'],
            ],
            [
                'key' => 'poultry_pricing.cooling_units_per_fan',
                'value' => '5.5',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'وحدات تبريد لكل شفاط',
                'label_en' => 'Cooling units per fan',
                'description' => 'أطوال وحدات التبريد لكل شفاط خلفي',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 10,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.windows_offset',
                'value' => '4',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'الفرق بين طول العنبر وعدد الشبابيك',
                'label_en' => 'Windows offset',
                'description' => 'القيمة المخصومة من الطول لحساب عدد الشبابيك',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 11,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.cooling_unit_price',
                'value' => '1800',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'سعر وحدة التبريد',
                'label_en' => 'Cooling unit price',
                'description' => 'سعر المتر من وحدات التبريد',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 12,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.window_unit_price',
                'value' => '450',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'سعر الشباك',
                'label_en' => 'Window unit price',
                'description' => 'سعر شباك التهوية الواحد',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 13,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.back_fan_unit_price',
                'value' => '12500',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'سعر الشفاط الخلفي',
                'label_en' => 'Back fan unit price',
                'description' => 'سعر الشفاط الخلفي الواحد',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 14,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.side_fan_unit_price',
                'value' => '8500',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'سعر الشفاط الجانبي',
                'label_en' => 'Side fan unit price',
                'description' => 'سعر الشفاط الجانبي الواحد',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 15,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.heater_unit_price',
                'value' => '9500',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'سعر الدفاية',
                'label_en' => 'Heater unit price',
                'description' => 'سعر الدفاية الواحدة',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 16,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.control_fixed_cost',
                'value' => '75000',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'تكلفة لوحة التحكم الثابتة',
                'label_en' => 'Control panel fixed cost',
                'description' => 'التكلفة الثابتة لنظام التحكم',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 17,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.include_tanks_default',
                'value' => '1',
                'type' => 'boolean',
                'category' => 'poultry_pricing',
                'label_ar' => 'تضمين الخزانات في التسعير',
                'label_en' => 'Include tanks in pricing',
                'description' => 'عند التفعيل يُضاف بند الخزانات الثابت تلقائياً في نطاق الإنشاءات',
                'is_public' => false,
                'is_required' => false,
                'sort_order' => 18,
                'validation_rules' => [],
            ],
            [
                'key' => 'poultry_pricing.price_per_bird_reference_weight_kg',
                'value' => '1.100',
                'type' => 'decimal',
                'category' => 'poultry_pricing',
                'label_ar' => 'الوزن المرجعي لسعر الطائر (كجم)',
                'label_en' => 'Price per bird reference weight (kg)',
                'description' => 'الوزن المرجعي الثابت لسعر الطائر في نظام البطاريات (سعر ثابت لا يتغير بتغير الوزن المعروض في الحاسبة)',
                'is_public' => false,
                'is_required' => true,
                'sort_order' => 19,
                'validation_rules' => ['numeric', 'min:0'],
            ],
            [
                'key' => 'poultry_pricing.broiler_height_options',
                'value' => '[3.7,4.0,4.5]',
                'type' => 'json',
                'category' => 'poultry_pricing',
                'label_ar' => 'خيارات الارتفاع — تسمين',
                'label_en' => 'Broiler height options',
                'description' => 'قائمة ارتفاعات عنابر التسمين المتاحة (JSON) — مثال: [3.7,4.0,4.5]',
                'is_public' => false,
                'is_required' => false,
                'sort_order' => 20,
                'validation_rules' => [],
            ],
            [
                'key' => 'poultry_pricing.layer_height_options',
                'value' => '[3.5,4.0,4.5]',
                'type' => 'json',
                'category' => 'poultry_pricing',
                'label_ar' => 'خيارات الارتفاع — بياض',
                'label_en' => 'Layer height options',
                'description' => 'قائمة ارتفاعات عنابر البياض المتاحة (JSON) — مثال: [3.5,4.0,4.5]',
                'is_public' => false,
                'is_required' => false,
                'sort_order' => 21,
                'validation_rules' => [],
            ],
        ];

        foreach ($settings as $setting) {
            Setting::updateOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }
}
